# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 10
# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/

:pidfile: tmp/pids/sidekiq.pid

:logfile: ./log/sidekiq.log

staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
